import {
  Customer,
  FilamentSpool,
  Order,
  Printer,
  Product,
  ProductionJob,
  ShippingRecord,
  StatusHistoryEntry,
  AuditLogEntry,
  SystemSettings,
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  businessName: 'PokeCraft 3D Prints',
  currency: 'GBP',
  currencySymbol: '£',
  defaultShippingProvider: 'Royal Mail',
  defaultPrinterId: 'printer-ad5x',
  electricityCostPerHour: 0.22,
  defaultPackagingCost: 0.45,
  defaultFilamentCostPerKg: 19.99,
  orderPrefix: 'PC-',
  nextOrderNumber: 1019,
  lowFilamentThresholdG: 180,
  notificationPreferences: {
    lowFilamentAlert: true,
    orderDeadlines: true,
    failedPrintAlert: true,
  },
};

export const INITIAL_PRINTERS: Printer[] = [
  {
    id: 'printer-ad5x',
    name: 'Flashforge AD5X',
    manufacturer: 'Flashforge',
    model: 'AD5X Multi-Material',
    status: 'PRINTING',
    ipAddress: '192.168.1.142',
    location: 'Workbench A1 - Main Print Bay',
    capabilities: {
      buildVolume: '220 x 220 x 220 mm',
      nozzleSize: '0.4mm High-Flow',
      maxTemp: 300,
      multiColor: true,
      highSpeed: true,
    },
    currentJobId: 'job-104',
    currentJobName: 'Pokemon Card Stand - Matte Black x 2',
    progressPercentage: 68,
    remainingMinutes: 42,
    notes: '0.4mm hardened steel nozzle fitted. Calibrated for 0.16mm optimal layer height.',
    createdAt: '2026-01-10T09:00:00.000Z',
    updatedAt: '2026-09-24T10:15:00.000Z',
  },
  {
    id: 'printer-adv5m',
    name: 'Flashforge Adventurer 5M',
    manufacturer: 'Flashforge',
    model: 'Adventurer 5M Pro',
    status: 'IDLE',
    ipAddress: '192.168.1.145',
    location: 'Workbench A2 - Secondary Bay',
    capabilities: {
      buildVolume: '220 x 220 x 220 mm',
      nozzleSize: '0.4mm Quick-Swap',
      maxTemp: 280,
      multiColor: false,
      highSpeed: true,
    },
    currentJobId: undefined,
    currentJobName: undefined,
    progressPercentage: 0,
    remainingMinutes: 0,
    notes: 'Ready for next queue job. PEI textured build plate cleaned and ready.',
    createdAt: '2026-01-15T11:30:00.000Z',
    updatedAt: '2026-09-24T09:40:00.000Z',
  },
];

export const INITIAL_FILAMENTS: FilamentSpool[] = [
  {
    id: 'spool-01',
    brand: 'Sunlu',
    material: 'PLA',
    color: 'Matte Charcoal Black',
    hexColor: '#1f2937',
    weightPurchasedG: 1000,
    remainingWeightG: 420,
    cost: 18.5,
    costPerGram: 0.0185,
    spoolStatus: 'In Use',
    location: 'Shelf 1 - Rack A',
    notes: 'Primary workhorse filament. 210°C / 60°C bed.',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-09-23T14:30:00.000Z',
  },
  {
    id: 'spool-02',
    brand: 'eSUN',
    material: 'Silk PLA',
    color: 'Silk Champion Gold',
    hexColor: '#eab308',
    weightPurchasedG: 1000,
    remainingWeightG: 680,
    cost: 22.0,
    costPerGram: 0.022,
    spoolStatus: 'In Stock',
    location: 'Shelf 1 - Rack B',
    notes: 'High sheen for display stands and trophy prints.',
    createdAt: '2026-08-15T11:00:00.000Z',
    updatedAt: '2026-09-22T08:20:00.000Z',
  },
  {
    id: 'spool-03',
    brand: 'Flashforge',
    material: 'PETG',
    color: 'Pure Arctic White',
    hexColor: '#f8fafc',
    weightPurchasedG: 1000,
    remainingWeightG: 850,
    cost: 21.0,
    costPerGram: 0.021,
    spoolStatus: 'In Stock',
    location: 'Shelf 2 - Sealed Drybox',
    notes: 'Used for desk organizers and outdoor planters. 240°C / 75°C.',
    createdAt: '2026-08-20T14:00:00.000Z',
    updatedAt: '2026-09-21T16:00:00.000Z',
  },
  {
    id: 'spool-04',
    brand: 'Polymaker',
    material: 'PLA',
    color: 'Starlight Nebula Purple',
    hexColor: '#7c3aed',
    weightPurchasedG: 1000,
    remainingWeightG: 135, // Low stock alert!
    cost: 24.5,
    costPerGram: 0.0245,
    spoolStatus: 'In Use',
    location: 'Shelf 1 - Rack C',
    notes: 'Low stock warning triggered. Popular for Pokemon card stands.',
    createdAt: '2026-07-28T09:00:00.000Z',
    updatedAt: '2026-09-24T08:00:00.000Z',
  },
  {
    id: 'spool-05',
    brand: 'Overture',
    material: 'TPU',
    color: 'Crimson Red 95A',
    hexColor: '#dc2626',
    weightPurchasedG: 1000,
    remainingWeightG: 550,
    cost: 26.0,
    costPerGram: 0.026,
    spoolStatus: 'In Stock',
    location: 'Shelf 2 - Drybox B',
    notes: 'Flexible TPU for Switch grip bumpers and vibration dampeners.',
    createdAt: '2026-08-10T12:00:00.000Z',
    updatedAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'spool-06',
    brand: 'Sunlu',
    material: 'PLA',
    color: 'Pine Forest Green',
    hexColor: '#15803d',
    weightPurchasedG: 1000,
    remainingWeightG: 720,
    cost: 18.5,
    costPerGram: 0.0185,
    spoolStatus: 'In Stock',
    location: 'Shelf 1 - Rack D',
    notes: 'Great matte finish for planters and tabletop terrain.',
    createdAt: '2026-08-25T15:00:00.000Z',
    updatedAt: '2026-09-20T11:00:00.000Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    sku: 'PF-PKM-STD-01',
    name: 'Pokemon Graded Card Display Stand',
    description: 'Precision angled display stand designed specifically for PSA, BGS, and CGC slabbed Pokemon & trading cards with stability lip.',
    imageUrl: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=600&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
    ],
    sellingPrice: 8.99,
    costPrice: 1.85,
    estimatedFilamentGrams: 55,
    estimatedPrintTimeMinutes: 110, // ~1h 50m
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PLA',
    defaultFilamentColor: 'Matte Charcoal Black',
    packagingType: 'Padded Jiffy Bag Small',
    isActive: true,
    variants: [
      { id: 'var-01a', name: 'Matte Black', sku: 'PF-PKM-STD-01-BLK', color: 'Matte Charcoal Black', priceModifier: 0 },
      { id: 'var-01b', name: 'Silk Gold Edition', sku: 'PF-PKM-STD-01-GLD', color: 'Silk Champion Gold', priceModifier: 1.5, filamentGramsModifier: 5 },
      { id: 'var-01c', name: 'Nebula Purple', sku: 'PF-PKM-STD-01-PUR', color: 'Starlight Nebula Purple', priceModifier: 1.0 },
    ],
    notes: 'Top seller on Etsy. Print with 3 perimeters and 15% gyroid infill.',
    createdAt: '2026-06-01T10:00:00.000Z',
    updatedAt: '2026-09-15T12:00:00.000Z',
  },
  {
    id: 'prod-02',
    sku: 'PF-TCG-TRIPLE-02',
    name: 'Triple Tier TCG Trading Card Showcase',
    description: 'Tiered 3-card elevated display stand for showcasing booster pack pulls and rare card collections.',
    imageUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 14.99,
    costPrice: 3.42,
    estimatedFilamentGrams: 115,
    estimatedPrintTimeMinutes: 210, // 3h 30m
    defaultPrinterId: 'printer-adv5m',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PLA',
    defaultFilamentColor: 'Matte Charcoal Black',
    packagingType: 'Small Cardboard Mailer Box C5',
    isActive: true,
    variants: [
      { id: 'var-02a', name: 'Standard Black', sku: 'PF-TCG-TRIPLE-BLK', color: 'Matte Charcoal Black', priceModifier: 0 },
      { id: 'var-02b', name: 'Gloss White', sku: 'PF-TCG-TRIPLE-WHT', color: 'Pure Arctic White', priceModifier: 0 },
    ],
    notes: 'High margin item. Pack with foam insert to prevent corner damage.',
    createdAt: '2026-06-15T14:00:00.000Z',
    updatedAt: '2026-09-10T11:00:00.000Z',
  },
  {
    id: 'prod-03',
    sku: 'PF-HEX-DESK-03',
    name: 'Hexagonal Modular Desk Organiser System',
    description: 'Interlocking honeycomb pen, SD card, tool, and USB flash drive desktop storage module.',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 12.5,
    costPrice: 2.75,
    estimatedFilamentGrams: 90,
    estimatedPrintTimeMinutes: 165,
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PETG',
    defaultFilamentColor: 'Pure Arctic White',
    packagingType: 'Medium Mailer Box',
    isActive: true,
    variants: [
      { id: 'var-03a', name: 'Arctic White (Set of 3)', sku: 'PF-HEX-3PK-WHT', color: 'Pure Arctic White', priceModifier: 0 },
      { id: 'var-03b', name: 'Forest Green Accent', sku: 'PF-HEX-3PK-GRN', color: 'Pine Forest Green', priceModifier: 0 },
    ],
    notes: 'Very durable in PETG, withstands warm sunlight without warping.',
    createdAt: '2026-07-01T09:00:00.000Z',
    updatedAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'prod-04',
    sku: 'PF-CBL-CLIP-04',
    name: 'Under-Desk Cable Management Raceway Clips (Pack of 6)',
    description: 'Heavy duty snap-latch cable clips with screw holes and 3M adhesive recess.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 9.99,
    costPrice: 1.4,
    estimatedFilamentGrams: 42,
    estimatedPrintTimeMinutes: 75,
    defaultPrinterId: 'printer-adv5m',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PETG',
    defaultFilamentColor: 'Matte Charcoal Black',
    packagingType: 'Padded Jiffy Bag Small',
    isActive: true,
    variants: [],
    notes: 'Fast print time, batch-print 12 at once on Adventurer 5M.',
    createdAt: '2026-07-10T13:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'prod-05',
    sku: 'PF-SWT-GRP-05',
    name: 'Ergonomic Comfort Grip for Nintendo Switch & OLED',
    description: 'Textured palm swells for extended handheld gaming sessions. Lightweight and balanced.',
    imageUrl: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 16.99,
    costPrice: 3.15,
    estimatedFilamentGrams: 105,
    estimatedPrintTimeMinutes: 220,
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PLA',
    defaultFilamentColor: 'Matte Charcoal Black',
    packagingType: 'Medium Mailer Box',
    isActive: true,
    variants: [
      { id: 'var-05a', name: 'Stealth Black', sku: 'PF-SWT-GRP-BLK', color: 'Matte Charcoal Black', priceModifier: 0 },
      { id: 'var-05b', name: 'Nebula Violet', sku: 'PF-SWT-GRP-PUR', color: 'Starlight Nebula Purple', priceModifier: 2.0 },
    ],
    notes: 'Print with tree supports touching buildplate only.',
    createdAt: '2026-07-20T11:00:00.000Z',
    updatedAt: '2026-09-18T14:00:00.000Z',
  },
  {
    id: 'prod-06',
    sku: 'PF-LITHO-FRM-06',
    name: 'Curved Lithophane LED Backlight Desk Frame',
    description: 'Custom curved photo lamp frame designed to snap fit a 3D printed lithophane photograph.',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 24.99,
    costPrice: 5.2,
    estimatedFilamentGrams: 160,
    estimatedPrintTimeMinutes: 340, // 5h 40m
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x'],
    material: 'PLA',
    defaultFilamentColor: 'Pure Arctic White',
    packagingType: 'Rigid Presentation Box',
    isActive: true,
    variants: [],
    notes: 'Premium gift product. Includes USB LED warm white light puck.',
    createdAt: '2026-08-01T15:00:00.000Z',
    updatedAt: '2026-09-12T09:00:00.000Z',
  },
  {
    id: 'prod-07',
    sku: 'PF-HPH-STD-07',
    name: 'Architectural Minimalist Headphone Stand',
    description: 'Swept cantilever curved stand providing gentle headrest contour to prevent headband creases.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 19.99,
    costPrice: 4.6,
    estimatedFilamentGrams: 175,
    estimatedPrintTimeMinutes: 310,
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PLA',
    defaultFilamentColor: 'Matte Charcoal Black',
    packagingType: 'Large Mailer Box',
    isActive: true,
    variants: [
      { id: 'var-07a', name: 'Matte Black', sku: 'PF-HPH-STD-BLK', color: 'Matte Charcoal Black', priceModifier: 0 },
      { id: 'var-07b', name: 'Silk Gold Head', sku: 'PF-HPH-STD-GLD', color: 'Silk Champion Gold', priceModifier: 3.0 },
    ],
    notes: 'Weighted base recess fits 4x M10 washers for stability.',
    createdAt: '2026-08-05T12:00:00.000Z',
    updatedAt: '2026-09-14T10:00:00.000Z',
  },
  {
    id: 'prod-08',
    sku: 'PF-GRID-SET-08',
    name: 'Gridfinity Workshop Tool Tray 4-Compartment',
    description: 'Zack Freedman standard Gridfinity 2x3 base tray for screws, drill bits, and craft components.',
    imageUrl: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 7.5,
    costPrice: 1.6,
    estimatedFilamentGrams: 58,
    estimatedPrintTimeMinutes: 95,
    defaultPrinterId: 'printer-adv5m',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PETG',
    defaultFilamentColor: 'Pine Forest Green',
    packagingType: 'Padded Jiffy Bag Medium',
    isActive: true,
    variants: [],
    notes: 'Gridfinity standard with 6x2mm magnet holes.',
    createdAt: '2026-08-10T14:00:00.000Z',
    updatedAt: '2026-09-16T15:00:00.000Z',
  },
  {
    id: 'prod-09',
    sku: 'PF-GEO-PLANT-09',
    name: 'Low-Poly Geometric Succulent Planter with Saucer',
    description: 'Faceted modern indoor planter with hidden water drainage holes and detachable drip saucer.',
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 11.99,
    costPrice: 2.3,
    estimatedFilamentGrams: 75,
    estimatedPrintTimeMinutes: 140,
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'PLA',
    defaultFilamentColor: 'Pine Forest Green',
    packagingType: 'Cardboard Mailer Box C5',
    isActive: true,
    variants: [
      { id: 'var-09a', name: 'Forest Green', sku: 'PF-GEO-PLANT-GRN', color: 'Pine Forest Green', priceModifier: 0 },
      { id: 'var-09b', name: 'Arctic White', sku: 'PF-GEO-PLANT-WHT', color: 'Pure Arctic White', priceModifier: 0 },
    ],
    notes: 'Print saucer with 100% infill for guaranteed waterproofing.',
    createdAt: '2026-08-15T09:30:00.000Z',
    updatedAt: '2026-09-19T13:00:00.000Z',
  },
  {
    id: 'prod-10',
    sku: 'PF-ARTIC-DRAG-10',
    name: 'Articulated Crystal Wing Dragon (Print-in-Place)',
    description: 'Fully flexible print-in-place fidget dragon with articulated spine, ball socket wings, and detailed scales.',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
    additionalImages: [],
    sellingPrice: 18.99,
    costPrice: 3.9,
    estimatedFilamentGrams: 130,
    estimatedPrintTimeMinutes: 280,
    defaultPrinterId: 'printer-ad5x',
    compatiblePrinters: ['printer-ad5x', 'printer-adv5m'],
    material: 'Silk PLA',
    defaultFilamentColor: 'Silk Champion Gold',
    packagingType: 'Cardboard Mailer Box C5',
    isActive: true,
    variants: [
      { id: 'var-10a', name: 'Silk Gold Dragon', sku: 'PF-DRAG-GLD', color: 'Silk Champion Gold', priceModifier: 0 },
      { id: 'var-10b', name: 'Nebula Purple Dragon', sku: 'PF-DRAG-PUR', color: 'Starlight Nebula Purple', priceModifier: 0 },
    ],
    notes: 'Requires perfect first layer bed adhesion. Wash plate with dish soap before printing.',
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-09-22T17:00:00.000Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-01',
    name: 'Marcus Vance',
    email: 'marcus.vance88@gmail.com',
    phone: '+44 7700 900142',
    address: {
      street: '14 Elmwood Crescent',
      city: 'Manchester',
      stateOrCounty: 'Greater Manchester',
      postcode: 'M14 6YP',
      country: 'United Kingdom',
    },
    notes: 'Avid Pokemon TCG collector. Frequently orders custom stands in gold & purple.',
    createdAt: '2026-06-12T11:20:00.000Z',
    updatedAt: '2026-09-20T14:10:00.000Z',
  },
  {
    id: 'cust-02',
    name: 'Sophie Davies',
    email: 'sophie.davies@outlook.com',
    phone: '+44 7700 900519',
    address: {
      street: '42 Highfield Lane',
      city: 'Bristol',
      stateOrCounty: 'City of Bristol',
      postcode: 'BS8 2EU',
      country: 'United Kingdom',
    },
    notes: 'Ordered modular desk organizer set for her design studio.',
    createdAt: '2026-07-04T16:00:00.000Z',
    updatedAt: '2026-09-18T10:30:00.000Z',
  },
  {
    id: 'cust-03',
    name: 'Liam Gallagher',
    email: 'liam.g.collects@yahoo.co.uk',
    phone: '+44 7700 900388',
    address: {
      street: '7 Victoria Road',
      city: 'Leeds',
      stateOrCounty: 'West Yorkshire',
      postcode: 'LS6 1AS',
      country: 'United Kingdom',
    },
    notes: 'Etsy repeat customer. Prefers Royal Mail Tracked 24.',
    createdAt: '2026-07-15T09:45:00.000Z',
    updatedAt: '2026-09-23T11:00:00.000Z',
  },
  {
    id: 'cust-04',
    name: 'Emma Richardson',
    email: 'emma.richardson@me.com',
    phone: '+44 7700 900741',
    address: {
      street: '88 Meadow Way',
      city: 'Birmingham',
      stateOrCounty: 'West Midlands',
      postcode: 'B15 2TT',
      country: 'United Kingdom',
    },
    notes: 'Purchased comfort grips for Nintendo Switch OLED.',
    createdAt: '2026-08-02T13:10:00.000Z',
    updatedAt: '2026-09-14T15:20:00.000Z',
  },
  {
    id: 'cust-05',
    name: 'Oliver Thorne',
    email: 'oliver.thorne@gmail.com',
    phone: '+44 7700 900892',
    address: {
      street: '19 Queensgate Mews',
      city: 'London',
      stateOrCounty: 'Kensington',
      postcode: 'SW7 5JJ',
      country: 'United Kingdom',
    },
    notes: 'Ordered headphone stand and matching desk accessories.',
    createdAt: '2026-08-11T10:30:00.000Z',
    updatedAt: '2026-09-21T09:15:00.000Z',
  },
  {
    id: 'cust-06',
    name: 'Chloe Bennett',
    email: 'chloe.bennett@sky.com',
    phone: '+44 7700 900632',
    address: {
      street: '55 St Andrews Terrace',
      city: 'Edinburgh',
      stateOrCounty: 'Midlothian',
      postcode: 'EH1 2PB',
      country: 'United Kingdom',
    },
    notes: 'Purchased articulated crystal dragons as birthday gifts.',
    createdAt: '2026-08-18T14:20:00.000Z',
    updatedAt: '2026-09-22T16:45:00.000Z',
  },
  {
    id: 'cust-07',
    name: 'Daniel Wright',
    email: 'dan.wright.3d@gmail.com',
    phone: '+44 7700 900215',
    address: {
      street: '12 Castle Hill',
      city: 'Nottingham',
      stateOrCounty: 'Nottinghamshire',
      postcode: 'NG1 6AA',
      country: 'United Kingdom',
    },
    notes: 'Purchased Gridfinity organizers for home garage workshop.',
    createdAt: '2026-08-25T11:00:00.000Z',
    updatedAt: '2026-09-19T14:00:00.000Z',
  },
  {
    id: 'cust-08',
    name: 'Hannah Brooks',
    email: 'hannah.brooks@hotmail.co.uk',
    phone: '+44 7700 900977',
    address: {
      street: '23 Marina Drive',
      city: 'Southampton',
      stateOrCounty: 'Hampshire',
      postcode: 'SO14 3TL',
      country: 'United Kingdom',
    },
    notes: 'Ordered custom Lithophane desk lamp for wedding anniversary.',
    createdAt: '2026-09-01T08:50:00.000Z',
    updatedAt: '2026-09-23T16:00:00.000Z',
  },
  {
    id: 'cust-09',
    name: 'Jack Harrison',
    email: 'jack.harrison.tech@gmail.com',
    phone: '+44 7700 900443',
    address: {
      street: '9 Orchard Close',
      city: 'Cambridge',
      stateOrCounty: 'Cambridgeshire',
      postcode: 'CB2 1LA',
      country: 'United Kingdom',
    },
    notes: 'Facebook Marketplace buyer, picked up cable raceways.',
    createdAt: '2026-09-08T15:30:00.000Z',
    updatedAt: '2026-09-17T11:30:00.000Z',
  },
  {
    id: 'cust-10',
    name: 'Aisha Patel',
    email: 'aisha.patel@cardiff.ac.uk',
    phone: '+44 7700 900118',
    address: {
      street: '31 Park Place',
      city: 'Cardiff',
      stateOrCounty: 'South Glamorgan',
      postcode: 'CF10 3BA',
      country: 'United Kingdom',
    },
    notes: 'Bought multiple geometric succulent planters for student dorms.',
    createdAt: '2026-09-12T12:15:00.000Z',
    updatedAt: '2026-09-24T09:00:00.000Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order-1018',
    internalOrderId: 'PF-1018',
    externalOrderId: 'ETSY-39481029',
    salesChannel: 'Etsy',
    orderDate: '2026-09-24T08:15:00.000Z',
    customerId: 'cust-01',
    customerName: 'Marcus Vance',
    customerEmail: 'marcus.vance88@gmail.com',
    customerPhone: '+44 7700 900142',
    billingAddress: '14 Elmwood Crescent, Manchester, M14 6YP, UK',
    shippingAddress: '14 Elmwood Crescent, Manchester, M14 6YP, UK',
    items: [
      {
        id: 'item-1018-1',
        orderId: 'order-1018',
        productId: 'prod-01',
        productName: 'Pokemon Graded Card Display Stand',
        variantId: 'var-01a',
        variantName: 'Matte Black',
        quantity: 2,
        unitPrice: 8.99,
        costPrice: 1.85,
        filamentGramsPerUnit: 55,
        printTimeMinutesPerUnit: 110,
        subtotal: 17.98,
      },
    ],
    subtotal: 17.98,
    shippingCost: 3.2,
    discount: 0,
    total: 21.18,
    productCost: 3.7,
    estimatedProfit: 14.28,
    paymentStatus: 'Paid',
    status: 'PRINTING',
    productionStatus: 'Printing',
    packingStatus: 'Unpacked',
    shippingStatus: 'Unfulfilled',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    customerNotes: 'Please wrap carefully so stands do not scuff during transit.',
    internalNotes: 'Currently printing on Flashforge AD5X.',
    createdAt: '2026-09-24T08:15:00.000Z',
    updatedAt: '2026-09-24T10:15:00.000Z',
  },
  {
    id: 'order-1017',
    internalOrderId: 'PF-1017',
    externalOrderId: 'EBAY-92817402',
    salesChannel: 'eBay',
    orderDate: '2026-09-24T06:30:00.000Z',
    customerId: 'cust-03',
    customerName: 'Liam Gallagher',
    customerEmail: 'liam.g.collects@yahoo.co.uk',
    billingAddress: '7 Victoria Road, Leeds, LS6 1AS, UK',
    shippingAddress: '7 Victoria Road, Leeds, LS6 1AS, UK',
    items: [
      {
        id: 'item-1017-1',
        orderId: 'order-1017',
        productId: 'prod-02',
        productName: 'Triple Tier TCG Trading Card Showcase',
        variantId: 'var-02a',
        variantName: 'Standard Black',
        quantity: 1,
        unitPrice: 14.99,
        costPrice: 3.42,
        filamentGramsPerUnit: 115,
        printTimeMinutesPerUnit: 210,
        subtotal: 14.99,
      },
    ],
    subtotal: 14.99,
    shippingCost: 3.85,
    discount: 0,
    total: 18.84,
    productCost: 3.42,
    estimatedProfit: 11.57,
    paymentStatus: 'Paid',
    status: 'AWAITING PRINT',
    productionStatus: 'Awaiting Print',
    packingStatus: 'Unpacked',
    shippingStatus: 'Unfulfilled',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 24',
    customerNotes: 'Priority dispatch requested if possible!',
    internalNotes: 'Next in queue for Flashforge Adventurer 5M.',
    createdAt: '2026-09-24T06:30:00.000Z',
    updatedAt: '2026-09-24T07:00:00.000Z',
  },
  {
    id: 'order-1016',
    internalOrderId: 'PF-1016',
    externalOrderId: 'WEB-4821',
    salesChannel: 'Website',
    orderDate: '2026-09-23T19:40:00.000Z',
    customerId: 'cust-06',
    customerName: 'Chloe Bennett',
    customerEmail: 'chloe.bennett@sky.com',
    billingAddress: '55 St Andrews Terrace, Edinburgh, EH1 2PB, UK',
    shippingAddress: '55 St Andrews Terrace, Edinburgh, EH1 2PB, UK',
    items: [
      {
        id: 'item-1016-1',
        orderId: 'order-1016',
        productId: 'prod-10',
        productName: 'Articulated Crystal Wing Dragon (Print-in-Place)',
        variantId: 'var-10a',
        variantName: 'Silk Gold Dragon',
        quantity: 1,
        unitPrice: 18.99,
        costPrice: 3.9,
        filamentGramsPerUnit: 130,
        printTimeMinutesPerUnit: 280,
        subtotal: 18.99,
      },
    ],
    subtotal: 18.99,
    shippingCost: 3.5,
    discount: 1.5,
    total: 20.99,
    productCost: 3.9,
    estimatedProfit: 13.59,
    paymentStatus: 'Paid',
    status: 'PRINTED',
    productionStatus: 'Printed',
    packingStatus: 'Packing',
    shippingStatus: 'Unfulfilled',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    customerNotes: 'Birthday gift on Saturday.',
    internalNotes: 'Printed cleanly in Silk Gold. Passed visual quality inspection.',
    createdAt: '2026-09-23T19:40:00.000Z',
    updatedAt: '2026-09-24T09:20:00.000Z',
  },
  {
    id: 'order-1015',
    internalOrderId: 'PF-1015',
    externalOrderId: 'ETSY-84729114',
    salesChannel: 'Etsy',
    orderDate: '2026-09-23T15:10:00.000Z',
    customerId: 'cust-04',
    customerName: 'Emma Richardson',
    customerEmail: 'emma.richardson@me.com',
    billingAddress: '88 Meadow Way, Birmingham, B15 2TT, UK',
    shippingAddress: '88 Meadow Way, Birmingham, B15 2TT, UK',
    items: [
      {
        id: 'item-1015-1',
        orderId: 'order-1015',
        productId: 'prod-05',
        productName: 'Ergonomic Comfort Grip for Nintendo Switch & OLED',
        variantId: 'var-05a',
        variantName: 'Stealth Black',
        quantity: 1,
        unitPrice: 16.99,
        costPrice: 3.15,
        filamentGramsPerUnit: 105,
        printTimeMinutesPerUnit: 220,
        subtotal: 16.99,
      },
    ],
    subtotal: 16.99,
    shippingCost: 3.2,
    discount: 0,
    total: 20.19,
    productCost: 3.15,
    estimatedProfit: 13.84,
    paymentStatus: 'Paid',
    status: 'READY TO SHIP',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Label Created',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    trackingNumber: 'RM492019482GB',
    customerNotes: '',
    internalNotes: 'Boxed in C5 mailer. Label printed and attached.',
    createdAt: '2026-09-23T15:10:00.000Z',
    updatedAt: '2026-09-24T10:00:00.000Z',
  },
  {
    id: 'order-1014',
    internalOrderId: 'PF-1014',
    externalOrderId: 'FB-9382104',
    salesChannel: 'Facebook Marketplace',
    orderDate: '2026-09-23T12:00:00.000Z',
    customerId: 'cust-09',
    customerName: 'Jack Harrison',
    customerEmail: 'jack.harrison.tech@gmail.com',
    billingAddress: '9 Orchard Close, Cambridge, CB2 1LA, UK',
    shippingAddress: '9 Orchard Close, Cambridge, CB2 1LA, UK',
    items: [
      {
        id: 'item-1014-1',
        orderId: 'order-1014',
        productId: 'prod-04',
        productName: 'Under-Desk Cable Management Raceway Clips (Pack of 6)',
        quantity: 2,
        unitPrice: 9.99,
        costPrice: 1.4,
        filamentGramsPerUnit: 42,
        printTimeMinutesPerUnit: 75,
        subtotal: 19.98,
      },
    ],
    subtotal: 19.98,
    shippingCost: 2.8,
    discount: 0,
    total: 22.78,
    productCost: 2.8,
    estimatedProfit: 17.18,
    paymentStatus: 'Paid',
    status: 'SHIPPED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Shipped',
    shippingProvider: 'Evri',
    shippingService: 'Standard Delivery',
    trackingNumber: 'EVR891048123',
    customerNotes: '',
    internalNotes: 'Dispatched via local Evri parcelshop drop-off.',
    createdAt: '2026-09-23T12:00:00.000Z',
    updatedAt: '2026-09-24T08:30:00.000Z',
  },
  {
    id: 'order-1013',
    internalOrderId: 'PF-1013',
    externalOrderId: 'ETSY-73819201',
    salesChannel: 'Etsy',
    orderDate: '2026-09-22T14:30:00.000Z',
    customerId: 'cust-05',
    customerName: 'Oliver Thorne',
    customerEmail: 'oliver.thorne@gmail.com',
    billingAddress: '19 Queensgate Mews, London, SW7 5JJ, UK',
    shippingAddress: '19 Queensgate Mews, London, SW7 5JJ, UK',
    items: [
      {
        id: 'item-1013-1',
        orderId: 'order-1013',
        productId: 'prod-07',
        productName: 'Architectural Minimalist Headphone Stand',
        variantId: 'var-07a',
        variantName: 'Matte Black',
        quantity: 1,
        unitPrice: 19.99,
        costPrice: 4.6,
        filamentGramsPerUnit: 175,
        printTimeMinutesPerUnit: 310,
        subtotal: 19.99,
      },
    ],
    subtotal: 19.99,
    shippingCost: 4.5,
    discount: 0,
    total: 24.49,
    productCost: 4.6,
    estimatedProfit: 15.39,
    paymentStatus: 'Paid',
    status: 'COMPLETED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Delivered',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 24',
    trackingNumber: 'RM381928410GB',
    customerNotes: '',
    internalNotes: 'Delivered on 23rd Sept. Customer left 5-star Etsy review.',
    createdAt: '2026-09-22T14:30:00.000Z',
    updatedAt: '2026-09-23T17:00:00.000Z',
  },
  {
    id: 'order-1012',
    internalOrderId: 'PF-1012',
    externalOrderId: 'MAN-0021',
    salesChannel: 'Manual',
    orderDate: '2026-09-22T10:15:00.000Z',
    customerId: 'cust-08',
    customerName: 'Hannah Brooks',
    customerEmail: 'hannah.brooks@hotmail.co.uk',
    billingAddress: '23 Marina Drive, Southampton, SO14 3TL, UK',
    shippingAddress: '23 Marina Drive, Southampton, SO14 3TL, UK',
    items: [
      {
        id: 'item-1012-1',
        orderId: 'order-1012',
        productId: 'prod-06',
        productName: 'Curved Lithophane LED Backlight Desk Frame',
        quantity: 1,
        unitPrice: 24.99,
        costPrice: 5.2,
        filamentGramsPerUnit: 160,
        printTimeMinutesPerUnit: 340,
        subtotal: 24.99,
      },
    ],
    subtotal: 24.99,
    shippingCost: 4.2,
    discount: 0,
    total: 29.19,
    productCost: 5.2,
    estimatedProfit: 19.79,
    paymentStatus: 'Paid',
    status: 'COMPLETED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Delivered',
    shippingProvider: 'DPD',
    shippingService: 'Next Day',
    trackingNumber: 'DPD159203918',
    customerNotes: 'Anniversary photo lamp.',
    internalNotes: 'White PETG frame with warm LED module.',
    createdAt: '2026-09-22T10:15:00.000Z',
    updatedAt: '2026-09-23T16:00:00.000Z',
  },
  {
    id: 'order-1011',
    internalOrderId: 'PF-1011',
    externalOrderId: 'ETSY-61928410',
    salesChannel: 'Etsy',
    orderDate: '2026-09-21T18:00:00.000Z',
    customerId: 'cust-10',
    customerName: 'Aisha Patel',
    customerEmail: 'aisha.patel@cardiff.ac.uk',
    billingAddress: '31 Park Place, Cardiff, CF10 3BA, UK',
    shippingAddress: '31 Park Place, Cardiff, CF10 3BA, UK',
    items: [
      {
        id: 'item-1011-1',
        orderId: 'order-1011',
        productId: 'prod-09',
        productName: 'Low-Poly Geometric Succulent Planter with Saucer',
        variantId: 'var-09a',
        variantName: 'Forest Green',
        quantity: 2,
        unitPrice: 11.99,
        costPrice: 2.3,
        filamentGramsPerUnit: 75,
        printTimeMinutesPerUnit: 140,
        subtotal: 23.98,
      },
    ],
    subtotal: 23.98,
    shippingCost: 3.5,
    discount: 2.0,
    total: 25.48,
    productCost: 4.6,
    estimatedProfit: 17.38,
    paymentStatus: 'Paid',
    status: 'COMPLETED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Delivered',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    trackingNumber: 'RM847291048GB',
    customerNotes: '',
    internalNotes: 'Delivered successfully.',
    createdAt: '2026-09-21T18:00:00.000Z',
    updatedAt: '2026-09-23T12:00:00.000Z',
  },
  {
    id: 'order-1010',
    internalOrderId: 'PF-1010',
    externalOrderId: 'EBAY-71928419',
    salesChannel: 'eBay',
    orderDate: '2026-09-21T11:20:00.000Z',
    customerId: 'cust-07',
    customerName: 'Daniel Wright',
    customerEmail: 'dan.wright.3d@gmail.com',
    billingAddress: '12 Castle Hill, Nottingham, NG1 6AA, UK',
    shippingAddress: '12 Castle Hill, Nottingham, NG1 6AA, UK',
    items: [
      {
        id: 'item-1010-1',
        orderId: 'order-1010',
        productId: 'prod-08',
        productName: 'Gridfinity Workshop Tool Tray 4-Compartment',
        quantity: 3,
        unitPrice: 7.5,
        costPrice: 1.6,
        filamentGramsPerUnit: 58,
        printTimeMinutesPerUnit: 95,
        subtotal: 22.5,
      },
    ],
    subtotal: 22.5,
    shippingCost: 3.2,
    discount: 0,
    total: 25.7,
    productCost: 4.8,
    estimatedProfit: 17.7,
    paymentStatus: 'Paid',
    status: 'COMPLETED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Delivered',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    trackingNumber: 'RM194829104GB',
    customerNotes: '',
    internalNotes: 'Workshop customer.',
    createdAt: '2026-09-21T11:20:00.000Z',
    updatedAt: '2026-09-23T10:00:00.000Z',
  },
  {
    id: 'order-1009',
    internalOrderId: 'PF-1009',
    externalOrderId: 'ETSY-51829103',
    salesChannel: 'Etsy',
    orderDate: '2026-09-20T16:40:00.000Z',
    customerId: 'cust-02',
    customerName: 'Sophie Davies',
    customerEmail: 'sophie.davies@outlook.com',
    billingAddress: '42 Highfield Lane, Bristol, BS8 2EU, UK',
    shippingAddress: '42 Highfield Lane, Bristol, BS8 2EU, UK',
    items: [
      {
        id: 'item-1009-1',
        orderId: 'order-1009',
        productId: 'prod-03',
        productName: 'Hexagonal Modular Desk Organiser System',
        variantId: 'var-03a',
        variantName: 'Arctic White (Set of 3)',
        quantity: 1,
        unitPrice: 12.5,
        costPrice: 2.75,
        filamentGramsPerUnit: 90,
        printTimeMinutesPerUnit: 165,
        subtotal: 12.5,
      },
    ],
    subtotal: 12.5,
    shippingCost: 3.2,
    discount: 0,
    total: 15.7,
    productCost: 2.75,
    estimatedProfit: 9.75,
    paymentStatus: 'Paid',
    status: 'COMPLETED',
    productionStatus: 'Printed',
    packingStatus: 'Packed',
    shippingStatus: 'Delivered',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    trackingNumber: 'RM918293819GB',
    customerNotes: '',
    internalNotes: '',
    createdAt: '2026-09-20T16:40:00.000Z',
    updatedAt: '2026-09-22T15:00:00.000Z',
  },
];

export const INITIAL_PRODUCTION_JOBS: ProductionJob[] = [
  {
    id: 'job-104',
    orderId: 'order-1018',
    orderInternalId: 'PF-1018',
    orderItemId: 'item-1018-1',
    productId: 'prod-01',
    productName: 'Pokemon Graded Card Display Stand',
    quantity: 2,
    printerId: 'printer-ad5x',
    printerName: 'Flashforge AD5X',
    status: 'printing',
    priority: 'HIGH',
    estimatedPrintTimeMinutes: 220,
    actualPrintTimeMinutes: 150,
    estimatedFilamentGrams: 110,
    material: 'PLA',
    color: 'Matte Charcoal Black',
    spoolId: 'spool-01',
    createdAt: '2026-09-24T08:20:00.000Z',
    startedAt: '2026-09-24T09:30:00.000Z',
    deadline: '2026-09-25T17:00:00.000Z',
    notes: 'Printing 2x simultaneously on textured PEI sheet.',
  },
  {
    id: 'job-103',
    orderId: 'order-1017',
    orderInternalId: 'PF-1017',
    orderItemId: 'item-1017-1',
    productId: 'prod-02',
    productName: 'Triple Tier TCG Trading Card Showcase',
    quantity: 1,
    printerId: 'printer-adv5m',
    printerName: 'Flashforge Adventurer 5M',
    status: 'awaiting_print',
    priority: 'URGENT',
    estimatedPrintTimeMinutes: 210,
    estimatedFilamentGrams: 115,
    material: 'PLA',
    color: 'Matte Charcoal Black',
    spoolId: 'spool-01',
    createdAt: '2026-09-24T07:05:00.000Z',
    deadline: '2026-09-25T12:00:00.000Z',
    notes: 'Customer requested rush dispatch. Load spool-01 before starting.',
  },
  {
    id: 'job-102',
    orderId: 'order-1016',
    orderInternalId: 'PF-1016',
    orderItemId: 'item-1016-1',
    productId: 'prod-10',
    productName: 'Articulated Crystal Wing Dragon (Print-in-Place)',
    quantity: 1,
    printerId: 'printer-ad5x',
    printerName: 'Flashforge AD5X',
    status: 'printed',
    priority: 'NORMAL',
    estimatedPrintTimeMinutes: 280,
    actualPrintTimeMinutes: 275,
    estimatedFilamentGrams: 130,
    actualFilamentGrams: 128,
    material: 'Silk PLA',
    color: 'Silk Champion Gold',
    spoolId: 'spool-02',
    createdAt: '2026-09-23T20:00:00.000Z',
    startedAt: '2026-09-24T03:00:00.000Z',
    completedAt: '2026-09-24T07:35:00.000Z',
    notes: 'Completed without stringing. Joints articulate cleanly.',
  },
  {
    id: 'job-101',
    orderId: 'order-1015',
    orderInternalId: 'PF-1015',
    orderItemId: 'item-1015-1',
    productId: 'prod-05',
    productName: 'Ergonomic Comfort Grip for Nintendo Switch & OLED',
    quantity: 1,
    printerId: 'printer-adv5m',
    printerName: 'Flashforge Adventurer 5M',
    status: 'printed',
    priority: 'NORMAL',
    estimatedPrintTimeMinutes: 220,
    actualPrintTimeMinutes: 215,
    estimatedFilamentGrams: 105,
    actualFilamentGrams: 104,
    material: 'PLA',
    color: 'Matte Charcoal Black',
    spoolId: 'spool-01',
    createdAt: '2026-09-23T15:30:00.000Z',
    startedAt: '2026-09-23T16:00:00.000Z',
    completedAt: '2026-09-23T19:35:00.000Z',
    notes: 'Supports removed cleanly with deburring tool.',
  },
];

export const INITIAL_SHIPPING_RECORDS: ShippingRecord[] = [
  {
    id: 'ship-1015',
    orderId: 'order-1015',
    orderInternalId: 'PF-1015',
    customerName: 'Emma Richardson',
    shippingAddress: '88 Meadow Way, Birmingham, B15 2TT, UK',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 48',
    trackingNumber: 'RM492019482GB',
    shippingCost: 3.2,
    labelStatus: 'Printed',
    shippedDate: undefined,
    createdAt: '2026-09-24T09:45:00.000Z',
  },
  {
    id: 'ship-1014',
    orderId: 'order-1014',
    orderInternalId: 'PF-1014',
    customerName: 'Jack Harrison',
    shippingAddress: '9 Orchard Close, Cambridge, CB2 1LA, UK',
    shippingProvider: 'Evri',
    shippingService: 'Standard Delivery',
    trackingNumber: 'EVR891048123',
    shippingCost: 2.8,
    labelStatus: 'Printed',
    shippedDate: '2026-09-24T08:30:00.000Z',
    createdAt: '2026-09-23T17:00:00.000Z',
  },
  {
    id: 'ship-1013',
    orderId: 'order-1013',
    orderInternalId: 'PF-1013',
    customerName: 'Oliver Thorne',
    shippingAddress: '19 Queensgate Mews, London, SW7 5JJ, UK',
    shippingProvider: 'Royal Mail',
    shippingService: 'Tracked 24',
    trackingNumber: 'RM381928410GB',
    shippingCost: 4.5,
    labelStatus: 'Printed',
    shippedDate: '2026-09-22T16:00:00.000Z',
    createdAt: '2026-09-22T15:00:00.000Z',
  },
];

export const INITIAL_STATUS_HISTORY: StatusHistoryEntry[] = [
  {
    id: 'hist-01',
    orderId: 'order-1018',
    orderInternalId: 'PF-1018',
    previousStatus: 'NEW',
    newStatus: 'CONFIRMED',
    timestamp: '2026-09-24T08:18:00.000Z',
    user: 'MattofTaylor@gmail.com',
    note: 'Payment verified from Etsy payout gateway.',
  },
  {
    id: 'hist-02',
    orderId: 'order-1018',
    orderInternalId: 'PF-1018',
    previousStatus: 'CONFIRMED',
    newStatus: 'AWAITING PRINT',
    timestamp: '2026-09-24T08:20:00.000Z',
    user: 'MattofTaylor@gmail.com',
    note: 'Created production job #job-104.',
  },
  {
    id: 'hist-03',
    orderId: 'order-1018',
    orderInternalId: 'PF-1018',
    previousStatus: 'AWAITING PRINT',
    newStatus: 'PRINTING',
    timestamp: '2026-09-24T09:30:00.000Z',
    user: 'MattofTaylor@gmail.com',
    note: 'Started print on Flashforge AD5X.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-01',
    action: 'Order created',
    entityType: 'Order',
    entityId: 'PF-1018',
    summary: 'New order PF-1018 imported from Etsy (Marcus Vance)',
    timestamp: '2026-09-24T08:15:00.000Z',
    user: 'Etsy Webhook (System)',
  },
  {
    id: 'audit-02',
    action: 'Production job started',
    entityType: 'Production',
    entityId: 'job-104',
    summary: 'Started job for 2x Pokemon Card Stand on Flashforge AD5X',
    timestamp: '2026-09-24T09:30:00.000Z',
    user: 'MattofTaylor@gmail.com',
  },
  {
    id: 'audit-03',
    action: 'Production job completed',
    entityType: 'Production',
    entityId: 'job-102',
    summary: 'Completed job for Articulated Crystal Wing Dragon. 128g Silk PLA logged.',
    timestamp: '2026-09-24T07:35:00.000Z',
    user: 'MattofTaylor@gmail.com',
  },
  {
    id: 'audit-04',
    action: 'Filament updated',
    entityType: 'Filament',
    entityId: 'spool-02',
    summary: 'Deducted 128g from eSUN Silk Champion Gold (spool-02)',
    timestamp: '2026-09-24T07:36:00.000Z',
    user: 'MattofTaylor@gmail.com',
  },
  {
    id: 'audit-05',
    action: 'Order status changed',
    entityType: 'Order',
    entityId: 'PF-1015',
    summary: 'Status updated to READY TO SHIP (Tracking: RM492019482GB)',
    timestamp: '2026-09-24T10:00:00.000Z',
    user: 'MattofTaylor@gmail.com',
  },
];
